=== AlexanderAdelAU/Rule-Propagated-Service-Orchestration/btsn.common.Monitor/PayLoad/payload.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="payload">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="header" />
				<xs:element ref="service" />
				<xs:element ref="joinAttribute" />
				<xs:element ref="monitorData" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="header">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="type" type="xs:string" />
				<xs:element name="ruleBaseVersion" type="xs:string" />
				<xs:element name="ruleBaseCommitment" type="xs:string" />
				<xs:element name="sequenceId" type="xs:string" />
				<xs:element name="priortiseSID" type="xs:string" />
				<xs:element name="monitorIncomingEvents" type="xs:string" />
				<xs:element name="activityCount" type="xs:string" />
				<xs:element name="status" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="service">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="serviceName" type="xs:NCName" />
				<xs:element name="operation" type="xs:NCName" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>


	<xs:element name="joinAttribute">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="attributeName" type="xs:string" />
				<xs:element name="attributeValue" type="xs:string" />
				<xs:element name="notBefore" type="xs:string" />
				<xs:element name="notAfter" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>



	<xs:element name="monitorData">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="callingService" type="xs:string" />
				<xs:element name="eventArrivalTime" type="xs:string" />
				<xs:element name="taskArrivalTime" type="xs:string" />
				<xs:element name="processStartTime" type="xs:string" />
				<xs:element name="processElapsedTime" type="xs:string" />
				<xs:element name="lostEvents" type="xs:string" />
				<xs:element name="eventGeneratorTimestamp" type="xs:string" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== AlexanderAdelAU/Rule-Propagated-Service-Orchestration/btsn.petrinet.places.p3/PayLoad/payload.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<payload xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="payload.xsd">
	<header>
		<type>process</type>
		<ruleBaseVersion>0</ruleBaseVersion>
		<ruleBaseCommitment>0</ruleBaseCommitment>
		<sequenceId>0</sequenceId>
		<priortiseSID>0</priortiseSID>
		<monitorIncomingEvents>true</monitorIncomingEvents>
		<activityCount>0</activityCount>
		<status>0</status>
	</header>

	<service>
		<serviceName>null</serviceName>
		<operation>null</operation>
	</service>
	
	<joinAttribute>
		<attributeName>0</attributeName>
		<attributeValue>0</attributeValue>
		<notBefore>0</notBefore>
		<notAfter>0</notAfter>
	</joinAttribute>
	
	<monitorData>
		<callingService>0</callingService>
		<eventArrivalTime>0</eventArrivalTime>
		<taskArrivalTime>0</taskArrivalTime>
		<processStartTime>0</processStartTime>
		<processElapsedTime>0</processElapsedTime>
		<lostEvents>0</lostEvents>
	</monitorData>
</payload>

=== AlexanderAdelAU/Rule-Propagated-Service-Orchestration/btsn.common.eventgenerators/v999/monitor_initializationservice_payload.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><payload xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="payload.xsd">
	<header>
		<type>process</type>
		<ruleBaseVersion>v999</ruleBaseVersion>
		<ruleBaseCommitment>0</ruleBaseCommitment>
		<sequenceId>0</sequenceId>
		<priortiseSID>true</priortiseSID>
		<monitorIncomingEvents>false</monitorIncomingEvents>
		<activityCount>0</activityCount>
		<status>0</status>
	</header>

	<service>
		<serviceName>Monitor_InitializationService</serviceName>
		<operation>purgeAndInitialize</operation>
	</service>
	
	<joinAttribute>
		<attributeName>token</attributeName>
		<attributeValue>"init monitor"</attributeValue>
		<notBefore>0</notBefore>
		<notAfter>0</notAfter>
	</joinAttribute>
	
	<monitorData>
		<callingService>0</callingService>
		<eventArrivalTime>0</eventArrivalTime>
		<taskArrivalTime>0</taskArrivalTime>
		<processStartTime>0</processStartTime>
		<processElapsedTime>0</processElapsedTime>
		<lostEvents>0</lostEvents>
	</monitorData>
</payload>
